apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      imagePullSecrets:       # THÊM DÒNG NÀY
        - name: ecr-registry-secret # KHỚP VỚI TÊN SECRET VỪA TẠO
      containers:
      - name: task-management
        image: task-management
        envFrom:
        - secretRef:
            name: task-management-secret
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC" # Tối ưu RAM cho container
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /task/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /task/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"