apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base              # Kế thừa từ bản gốc
namespace: dev              # Tự động đẩy mọi thứ vào namespace dev
namePrefix: dev-            # Tên app sẽ thành dev-task-management
images:
  - name: task-management         # Tìm image tên là task-management
    newName: 187104821419.dkr.ecr.ap-southeast-1.amazonaws.com/task-management
    newTag: latest          # Cái này sẽ được Jenkins ghi đè sau

commonLabels:
  env: dev